<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ImageCatalogProductSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            // AMPLIFIERS (Powered amplifiers)
            ['category' => 'AMPLIFIERS', 'model' => 'TX-200S', 'description' => '200W x 2 @ 8ohms, 2ohms stable with 2ch x-over', 'brand' => 'KEVLER', 'price' => '11900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'TX-400S', 'description' => '400W x 2 @ 8ohms, 2ohms stable with 2ch x-over', 'brand' => 'KEVLER', 'price' => '16500.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'TX-600S', 'description' => '600W x 2 @ 8ohms, 2ohms stable with 2ch x-over', 'brand' => 'KEVLER', 'price' => '19900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'TX-1000S', 'description' => '800W x 2 @ 8ohms, 2ohms stable with 2ch x-over', 'brand' => 'KEVLER', 'price' => '24900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'CRX-4600', 'description' => '600W x 4', 'brand' => 'KEVLER', 'price' => '29900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'CRX-21000', 'description' => '1000W x 2', 'brand' => 'KEVLER', 'price' => '27500.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'MZ-400', 'description' => '400W x 2 @ 8ohms, 2ohms stable', 'brand' => 'KEVLER', 'price' => '16990.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'MZ-600', 'description' => '600W x 2 @ 8ohms, 2ohms stable', 'brand' => 'KEVLER', 'price' => '21000.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'MZ-1000', 'description' => '1000W x 2 @ 8ohms, 2ohms stable', 'brand' => 'KEVLER', 'price' => '31000.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'ZX-5', 'description' => '1800W x 2 @ 8ohms', 'brand' => 'KEVLER', 'price' => '54900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'CA-2', 'description' => '300W x 2', 'brand' => 'MICKLE', 'price' => '11900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'CA-9', 'description' => '550W x 2 @ 8ohms, 825W x 2 @ 4ohms', 'brand' => 'MICKLE', 'price' => '19500.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'CA-12', 'description' => '800W x 2 @ 8ohms, 1200W x 2 @ 4ohms', 'brand' => 'MICKLE', 'price' => '22500.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'CA-18', 'description' => '1100W x 2 @ 8ohms, 1650W x 2 @ 4ohms', 'brand' => 'MICKLE', 'price' => '29500.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'CA-20', 'description' => '1300W x 2 @ 8ohms, 1950W x 2 @ 4ohms', 'brand' => 'MICKLE', 'price' => '32500.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'XP5000S', 'description' => '550W x 2 @ 8ohms (copper)', 'brand' => 'WEIPRO AUDIO CORP', 'price' => '11990.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'XP9500S', 'description' => '900W x 2 @ 8ohms (copper)', 'brand' => 'WEIPRO AUDIO CORP', 'price' => '17990.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'BL-600', 'description' => '350W x 2 @ 8ohms (copper)', 'brand' => 'WEIPRO AUDIO CORP', 'price' => '8990.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'BL-800', 'description' => '600W x 2 @ 8ohms (copper)', 'brand' => 'WEIPRO AUDIO CORP', 'price' => '10990.00'],

            // AMPLIFIERS (Integrated)
            ['category' => 'AMPLIFIERS', 'model' => 'GX-3UB PRO', 'description' => '300W x 2', 'brand' => 'KEVLER', 'price' => '4900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'GX-5PRO', 'description' => '600W x 2', 'brand' => 'KEVLER', 'price' => '5500.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'GX-5UB PRO', 'description' => '600W x 2', 'brand' => 'KEVLER', 'price' => '6500.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'GX-7PRO', 'description' => '800W x 2', 'brand' => 'KEVLER', 'price' => '7500.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'GX-7UB PRO', 'description' => '800W x 2', 'brand' => 'KEVLER', 'price' => '7500.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'GX-4000', 'description' => '900W x 2 with 4 mic input', 'brand' => 'KEVLER', 'price' => '9650.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'GX-5000', 'description' => '1000W x 2', 'brand' => 'KEVLER', 'price' => '10800.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'GX-7000', 'description' => '1500W x 2', 'brand' => 'KEVLER', 'price' => '11800.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'GX-8000', 'description' => '2000W x 2', 'brand' => 'KEVLER', 'price' => '14790.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'GX-10', 'description' => '800W x 2', 'brand' => 'KEVLER', 'price' => '8950.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'VAC-1000', 'description' => '850W x 2', 'brand' => 'KEVLER', 'price' => '8900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-993UB', 'description' => '80W x 2 with BT', 'brand' => 'SAKURA', 'price' => '2790.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-3023UB', 'description' => '350W x 2 with BT', 'brand' => 'SAKURA', 'price' => '4900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-5023UB', 'description' => '500W x 2', 'brand' => 'SAKURA', 'price' => '5650.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-733', 'description' => '450W x 2, 3 mic', 'brand' => 'SAKURA', 'price' => '7550.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-733UB', 'description' => '450W x 2, 3 mic', 'brand' => 'SAKURA', 'price' => '7950.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-735', 'description' => '700W x 2, 5 mic', 'brand' => 'SAKURA', 'price' => '6930.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-735UB', 'description' => '700W x 2 with BT, 5 mic', 'brand' => 'SAKURA', 'price' => '7950.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-737', 'description' => '1400W x 2', 'brand' => 'SAKURA', 'price' => '10600.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-737UB', 'description' => '1500W x 2 with BT, 5 mic', 'brand' => 'SAKURA', 'price' => '10800.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-739', 'description' => '750W x 2 (10ohm), 1400W x 2 (4ohm) with BT, 3 mic', 'brand' => 'SAKURA', 'price' => '7300.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-757UB', 'description' => '1750W x 2, 5 mic', 'brand' => 'SAKURA', 'price' => '11500.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-3UB', 'description' => '400W x 2', 'brand' => 'SAKURA', 'price' => '5290.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-5UB', 'description' => '600W x 2, 2 mic', 'brand' => 'SAKURA', 'price' => '5950.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-5000', 'description' => '1200W x 2', 'brand' => 'SAKURA', 'price' => '11200.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-9000', 'description' => '1800W x 2, 2 mic', 'brand' => 'SAKURA', 'price' => '11500.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-502C', 'description' => '58W, 5.1 channel', 'brand' => 'SAKURA', 'price' => '5550.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-602BT', 'description' => '500W x 2', 'brand' => 'SAMWON', 'price' => '5650.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'SW-800PRO', 'description' => '800W x 2', 'brand' => 'SAMWON', 'price' => '7700.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'AV-902', 'description' => '350W x 2', 'brand' => 'JOSON', 'price' => '3390.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'SATURN', 'description' => '1500W x 2', 'brand' => 'JOSON', 'price' => '7950.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'SATURN MAX', 'description' => null, 'brand' => 'JOSON', 'price' => '10650.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'JUPITER', 'description' => '380W', 'brand' => 'JOSON', 'price' => '9900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'JUPITER MAX', 'description' => '480W', 'brand' => 'JOSON', 'price' => '14900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'MARS', 'description' => '300W x 2', 'brand' => 'JOSON', 'price' => '3990.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'MARS PRO', 'description' => '350W x 2', 'brand' => 'JOSON', 'price' => '5200.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'EARTH 1.0', 'description' => null, 'brand' => 'JOSON', 'price' => '19500.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'SUN A-8', 'description' => '1200W', 'brand' => 'JOSON', 'price' => '18900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'URANUS', 'description' => '820W', 'brand' => 'JOSON', 'price' => '10900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'URANUS MAX', 'description' => null, 'brand' => 'JOSON', 'price' => '14900.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'MOON MAX', 'description' => '450W x 4', 'brand' => 'JOSON', 'price' => '12800.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'TO-5', 'description' => '450W x 2', 'brand' => 'TOSUNRA', 'price' => '3990.00'],
            ['category' => 'AMPLIFIERS', 'model' => 'TO-7', 'description' => '700W x 2', 'brand' => 'TOSUNRA', 'price' => '4590.00'],

            // BAFFLES
            ['category' => 'BAFFLES', 'model' => 'EON-8A', 'description' => '8" 100W 2-way full range active speaker', 'brand' => 'KEVLER', 'price' => '5900.00'],
            ['category' => 'BAFFLES', 'model' => 'EON-10A', 'description' => '10" 150W 2-way full range active speaker', 'brand' => 'KEVLER', 'price' => '7900.00'],
            ['category' => 'BAFFLES', 'model' => 'EON-12A', 'description' => '12" 250W 2-way full range active speaker', 'brand' => 'KEVLER', 'price' => '9900.00'],
            ['category' => 'BAFFLES', 'model' => 'EON-715D', 'description' => '15" 500W 2-way class D active speaker', 'brand' => 'KEVLER', 'price' => '15500.00'],
            ['category' => 'BAFFLES', 'model' => 'TWS-12D', 'description' => '12" 500W 2-way full range active speaker class D', 'brand' => 'KEVLER', 'price' => '11900.00'],
            ['category' => 'BAFFLES', 'model' => 'TWS-15D', 'description' => '15" 500W 2-way full range active speaker class D', 'brand' => 'KEVLER', 'price' => '14500.00'],
            ['category' => 'BAFFLES', 'model' => 'WAVE-12', 'description' => '12" 500W full range speaker', 'brand' => 'KEVLER', 'price' => '11900.00'],
            ['category' => 'BAFFLES', 'model' => 'WAVE-15', 'description' => '15" 800W full range speaker', 'brand' => 'KEVLER', 'price' => '15500.00'],
            ['category' => 'BAFFLES', 'model' => 'AXL-10', 'description' => '10" 350W 2-way bass reflex', 'brand' => 'KEVLER', 'price' => '10500.00'],
            ['category' => 'BAFFLES', 'model' => 'AXL-12', 'description' => '12" 700W 2-way bass reflex', 'brand' => 'KEVLER', 'price' => '14500.00'],
            ['category' => 'BAFFLES', 'model' => 'AXL-15', 'description' => '15" 1000W 2-way bass reflex', 'brand' => 'KEVLER', 'price' => '18500.00'],
            ['category' => 'BAFFLES', 'model' => 'ZLX-8', 'description' => '8" 250W 2-way full range speaker', 'brand' => 'KEVLER', 'price' => '8500.00'],
            ['category' => 'BAFFLES', 'model' => 'ZLX-8D', 'description' => '8" 250W full range active speaker', 'brand' => 'KEVLER', 'price' => '8200.00'],
            ['category' => 'BAFFLES', 'model' => 'ZLX-10', 'description' => '10" 350W 2-way full range speaker', 'brand' => 'KEVLER', 'price' => '10500.00'],
            ['category' => 'BAFFLES', 'model' => 'ZLX-10D', 'description' => '10" 300W 2-way full range active speaker', 'brand' => 'KEVLER', 'price' => '9500.00'],
            ['category' => 'BAFFLES', 'model' => 'ZLX-12', 'description' => '12" 700W 2-way full range speaker', 'brand' => 'KEVLER', 'price' => '14500.00'],
            ['category' => 'BAFFLES', 'model' => 'ZLX-12D', 'description' => '12D" 500W full range active speaker', 'brand' => 'KEVLER', 'price' => '12900.00'],
            ['category' => 'BAFFLES', 'model' => 'ZLX-15', 'description' => '15" 1000W 2-way full range speaker', 'brand' => 'KEVLER', 'price' => '18500.00'],
            ['category' => 'BAFFLES', 'model' => 'ZLX-15D', 'description' => '15" 500W 2-way full range active speaker', 'brand' => 'KEVLER', 'price' => '15500.00'],
            ['category' => 'BAFFLES', 'model' => 'PLX-12', 'description' => '12" 900W 2-way full range speaker', 'brand' => 'CROWN', 'price' => '13500.00'],
            ['category' => 'BAFFLES', 'model' => 'PLX-12A', 'description' => '12" 700W active speaker', 'brand' => 'CROWN', 'price' => '12500.00'],
            ['category' => 'BAFFLES', 'model' => 'PLX-15', 'description' => '15" 2000W P.M.P.O 2-way full range speaker', 'brand' => 'CROWN', 'price' => '15900.00'],
            ['category' => 'BAFFLES', 'model' => 'PLX-15A', 'description' => '15" 800W 2-way full range speaker', 'brand' => 'CROWN', 'price' => '14900.00'],
            ['category' => 'BAFFLES', 'model' => 'SLX-15', 'description' => '15" 1000W 2-way full range speaker', 'brand' => 'KEVLER', 'price' => '19900.00'],
            ['category' => 'BAFFLES', 'model' => 'SLX-15D', 'description' => '15" 500W 2-way full range active speaker', 'brand' => 'KEVLER', 'price' => '15900.00'],
            ['category' => 'BAFFLES', 'model' => 'KRX-612D', 'description' => '12" 800W 2-way full range speaker', 'brand' => 'KEVLER', 'price' => '33000.00'],
            ['category' => 'BAFFLES', 'model' => 'KRX-815D', 'description' => '15" 800W 2-way full range speaker', 'brand' => 'KEVLER', 'price' => '22000.00'],
            ['category' => 'BAFFLES', 'model' => 'PRX-825', 'description' => '15" dual 1400W 2-way pro full range speaker', 'brand' => 'KEVLER', 'price' => '47500.00'],
            ['category' => 'BAFFLES', 'model' => 'SRX-712M', 'description' => '12" 800W 2-way full range speaker', 'brand' => 'JBL', 'price' => '9900.00'],
            ['category' => 'BAFFLES', 'model' => 'SRX-715M', 'description' => '15" 800W 2-way full range speaker', 'brand' => 'JBL', 'price' => '16200.00'],
            ['category' => 'BAFFLES', 'model' => 'SRX-718SM', 'description' => '18" speaker box subwoofer', 'brand' => 'JBL', 'price' => '24500.00'],
            ['category' => 'BAFFLES', 'model' => 'IT AUDIO', 'description' => '15" 1000W 2-way full range active speaker', 'brand' => 'IT AUDIO', 'price' => '10500.00'],
            ['category' => 'BAFFLES', 'model' => 'A-9', 'description' => '15" 500W active subwoofer + 300W column speaker, 6pcs 3.5"', 'brand' => 'KEVLER', 'price' => '35000.00'],
            ['category' => 'BAFFLES', 'model' => 'A-10', 'description' => 'Active column speaker system, subwoofer 2x10" ferrite magnet tweeter, 600W (sub)+400W(column)', 'brand' => 'KEVLER', 'price' => '39900.00'],
            ['category' => 'BAFFLES', 'model' => 'A-12', 'description' => 'Array speaker (passive): low 6.5" mid bass driver, hi 1.5" titanium compression driver, 300W 96dB', 'brand' => 'KEVLER', 'price' => '47500.00'],
            ['category' => 'BAFFLES', 'model' => 'AIRBUS-15', 'description' => '15" 1500W passive speaker', 'brand' => 'JOSON', 'price' => '20500.00'],
            ['category' => 'BAFFLES', 'model' => 'FIGHTER 15', 'description' => '15" 1500W passive speaker', 'brand' => 'JOSON', 'price' => '13800.00'],
            ['category' => 'BAFFLES', 'model' => 'ART-715A', 'description' => '15" 1400W 2-way peak 130dB', 'brand' => 'JOSON', 'price' => '19500.00'],

            // CAR AMPLIFIERS AND ACCESSORIES
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'RST-100', 'description' => '4" 300W 3-way car speaker dual', 'brand' => 'PIONEER', 'price' => '650.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'RST-130', 'description' => '5" 500W 3-way car speaker dual', 'brand' => 'PIONEER', 'price' => '790.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'RST-160', 'description' => '6.5" 700W 3-way car speaker dual', 'brand' => 'PIONEER', 'price' => '890.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'TS-A1395S', 'description' => '5" 240W 2-way car speaker dual', 'brand' => 'PIONEER', 'price' => '850.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'TS-A1095S', 'description' => '4" 200W 2-way car speaker dual', 'brand' => 'PIONEER', 'price' => '890.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'TS-695SR', 'description' => '6x9" 600W 2-way car speaker dual', 'brand' => 'PIONEER', 'price' => '1395.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'WF-CX601', 'description' => '6" 80W dual cone', 'brand' => 'WINFORD', 'price' => '530.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'WF-CX602', 'description' => '6" 100W dual cone', 'brand' => 'WINFORD', 'price' => '790.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'CU-412', 'description' => '4" 100W 4-way dual', 'brand' => 'CROWN', 'price' => '890.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'CU-515', 'description' => '5" 150W 4-way dual', 'brand' => 'CROWN', 'price' => '990.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'CU-618', 'description' => '6" 170W 4-way dual', 'brand' => 'CROWN', 'price' => '1190.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'CU-517', 'description' => '5.5" 170W 2-way dual', 'brand' => 'CROWN', 'price' => '1290.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'MRV-55', 'description' => '5" 2-way speaker single', 'brand' => 'X12', 'price' => '290.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'MRV-56', 'description' => '6.5" 2-way speaker single', 'brand' => 'X12', 'price' => '350.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'MRV-SP5', 'description' => '5" 2-way car speaker dual', 'brand' => 'X12', 'price' => '790.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'GT-0402', 'description' => '4" 80W 2-way speaker dual', 'brand' => 'JBL', 'price' => '790.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'GT-052', 'description' => '5" 90W 2-way speaker dual', 'brand' => 'JBL', 'price' => '890.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'GT-0603', 'description' => '6.5" 125W 3-way speaker dual', 'brand' => 'JBL', 'price' => '1190.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'MRV-EQ200', 'description' => 'Parametric equalizer', 'brand' => 'X12', 'price' => '1490.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'MRV-EQ300', 'description' => 'Parametric equalizer', 'brand' => 'X12', 'price' => '1490.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'EQ-500', 'description' => '5 band equalizer', 'brand' => 'X12', 'price' => '1590.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'EQX-75PRO', 'description' => 'Parametric equalizer', 'brand' => 'BOSCHMANN', 'price' => '1490.00'],
            ['category' => 'CAR AMPLIFIERS AND ACCESSORIES', 'model' => 'SN-95BT', 'description' => 'Parametric equalizer with BT', 'brand' => 'BOSCHMANN', 'price' => '1690.00'],

            // PAGING AND CONFERENCE SYSTEM
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'BGM-300UB', 'description' => '180W PA zone amplifier with chime BT', 'brand' => 'KEVLER', 'price' => '10900.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'BGM-500UB', 'description' => '450W PA zone amplifier with chime BT', 'brand' => 'KEVLER', 'price' => '14900.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'PA-500', 'description' => '500W PA power amplifier 70/100V line', 'brand' => 'KEVLER', 'price' => '12900.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'PA-165UB', 'description' => '165W', 'brand' => 'SAKURA', 'price' => '3490.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'PA-225UB', 'description' => '225W', 'brand' => 'SAKURA', 'price' => '3990.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'PA-245UB', 'description' => '245W', 'brand' => 'SAKURA', 'price' => '5690.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'PA250UB', 'description' => '250W', 'brand' => 'SAKURA', 'price' => '7990.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'PA-500UB', 'description' => '500W', 'brand' => 'SAKURA', 'price' => '10900.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'PA-800UB', 'description' => '800W', 'brand' => 'SAKURA', 'price' => '12500.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'AM-300', 'description' => 'Conference system power supply', 'brand' => 'KEVLER', 'price' => '4200.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'AM-300C', 'description' => "Chairman's unit conference mic", 'brand' => 'KEVLER', 'price' => '2650.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'AM-300D', 'description' => "Delegate's unit conference mic", 'brand' => 'KEVLER', 'price' => '2550.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'LM-500', 'description' => 'Conference main unit recordable', 'brand' => 'KEVLER', 'price' => '7690.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'LM-501', 'description' => "Chairman's unit conference mic with speaker", 'brand' => 'KEVLER', 'price' => '3750.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'LM-502', 'description' => "Delegate's unit conference mic with speaker", 'brand' => 'KEVLER', 'price' => '3650.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'QM-900', 'description' => 'Conference main unit recordable (metal housing)', 'brand' => 'KEVLER', 'price' => '7900.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'QM-900C', 'description' => "Chairman's unit conference mic with speaker (metal housing)", 'brand' => 'KEVLER', 'price' => '4250.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'QM-900D', 'description' => "Delegate's unit conference mic with speaker (metal housing)", 'brand' => 'KEVLER', 'price' => '4000.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'TCM-1000V', 'description' => 'Wireless conference main unit recordable', 'brand' => 'KEVLER', 'price' => '14900.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'TCM-1000VC', 'description' => "Wireless conference chairman's unit", 'brand' => 'KEVLER', 'price' => '5850.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'TCM-1000VD', 'description' => "Wireless conference delegate's unit", 'brand' => 'KEVLER', 'price' => '5650.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'UR-8000', 'description' => "Wireless conference mic 8's", 'brand' => 'SHURE', 'price' => '21900.00'],
            ['category' => 'PAGING AND CONFERENCE SYSTEM', 'model' => 'CM-100UR', 'description' => 'Paging microphone with USB record and chime', 'brand' => 'KEVLER', 'price' => '3490.00'],

            // POWER TRANSFORMER
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-200MA', 'description' => 'Multi-tap transformer 200mA', 'brand' => 'TAMAGAWA', 'price' => '135.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-500MA', 'description' => 'Multi-tap transformer 500mA', 'brand' => 'TAMAGAWA', 'price' => '155.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-750MA', 'description' => 'Multi-tap transformer 750mA', 'brand' => 'TAMAGAWA', 'price' => '175.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-1A', 'description' => 'Multi-tap transformer 1A', 'brand' => 'TAMAGAWA', 'price' => '215.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-2A', 'description' => 'Multi-tap transformer 2A', 'brand' => 'TAMAGAWA', 'price' => '360.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-3A', 'description' => 'Multi-tap transformer 3A', 'brand' => 'TAMAGAWA', 'price' => '595.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-6A', 'description' => 'Multi-tap transformer 6A', 'brand' => 'TAMAGAWA', 'price' => '795.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-9V-1A', 'description' => '9V x 2 transformer 1A', 'brand' => 'TAMAGAWA', 'price' => '235.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-9V-2A', 'description' => '9V x 2 transformer 2A', 'brand' => 'TAMAGAWA', 'price' => '350.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-9V-3A', 'description' => '9V x 2 transformer 3A', 'brand' => 'TAMAGAWA', 'price' => '595.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-12V-200MA', 'description' => '12V x 2 transformer 200mA', 'brand' => 'TAMAGAWA', 'price' => '135.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-12V-500MA', 'description' => '12V x 2 transformer 500mA', 'brand' => 'TAMAGAWA', 'price' => '145.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-12V-750MA', 'description' => '12V x 2 transformer 750mA', 'brand' => 'TAMAGAWA', 'price' => '175.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-12V-1A', 'description' => '12V x 2 transformer 1A', 'brand' => 'TAMAGAWA', 'price' => '235.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-12V-2A', 'description' => '12V x 2 transformer 2A', 'brand' => 'TAMAGAWA', 'price' => '350.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-12V-3A', 'description' => '12V x 2 transformer 3A', 'brand' => 'TAMAGAWA', 'price' => '595.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-12V-6A', 'description' => '12V x 2 transformer 6A', 'brand' => 'TAMAGAWA', 'price' => '675.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-12V-12A', 'description' => '12V x 2 transformer 12A', 'brand' => 'TAMAGAWA', 'price' => '1110.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-12V-20A', 'description' => '12V x 2 transformer 20A', 'brand' => 'TAMAGAWA', 'price' => '1695.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-18V-3A', 'description' => '18V x 2 transformer 3A', 'brand' => 'TAMAGAWA', 'price' => '595.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-18V-6A', 'description' => '18V x 2 transformer 6A', 'brand' => 'TAMAGAWA', 'price' => '850.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-24V-1A', 'description' => '24V x 2 transformer 1A', 'brand' => 'TAMAGAWA', 'price' => '350.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-24V-2A', 'description' => '24V x 2 transformer 2A', 'brand' => 'TAMAGAWA', 'price' => '485.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-24V-3A', 'description' => '24V x 2 transformer 3A', 'brand' => 'TAMAGAWA', 'price' => '760.00'],
            ['category' => 'POWER TRANSFORMER', 'model' => 'MULTI-TAP-24V-6A', 'description' => '24V x 2 transformer 6A', 'brand' => 'TAMAGAWA', 'price' => '1050.00'],

            // STEPDOWN TRANSFORMER
            ['category' => 'STEPDOWN TRANSFORMER', 'model' => 'STEPDOWN-110V-50W', 'description' => '110V stepdown transformer 50W', 'brand' => 'TAMAGAWA', 'price' => '550.00'],
            ['category' => 'STEPDOWN TRANSFORMER', 'model' => 'STEPDOWN-110V-100W', 'description' => '110V stepdown transformer 100W', 'brand' => 'TAMAGAWA', 'price' => '730.00'],
            ['category' => 'STEPDOWN TRANSFORMER', 'model' => 'STEPDOWN-100V-100W', 'description' => '100V stepdown transformer 100W', 'brand' => 'TAMAGAWA', 'price' => '750.00'],
            ['category' => 'STEPDOWN TRANSFORMER', 'model' => 'STEPDOWN-100V-150W', 'description' => '100V stepdown transformer 150W', 'brand' => 'TAMAGAWA', 'price' => '1100.00'],
            ['category' => 'STEPDOWN TRANSFORMER', 'model' => 'STEPDOWN-100V-200W', 'description' => '100V stepdown transformer 200W', 'brand' => 'TAMAGAWA', 'price' => '1390.00'],
            ['category' => 'STEPDOWN TRANSFORMER', 'model' => 'STEPDOWN-100V-250W', 'description' => '100V stepdown transformer 250W', 'brand' => 'TAMAGAWA', 'price' => '1590.00'],
            ['category' => 'STEPDOWN TRANSFORMER', 'model' => 'STEPDOWN-100V-300W', 'description' => '100V stepdown transformer 300W', 'brand' => 'TAMAGAWA', 'price' => '1690.00'],
            ['category' => 'STEPDOWN TRANSFORMER', 'model' => 'STEPDOWN-100V-350W', 'description' => '100V stepdown transformer 350W', 'brand' => 'TAMAGAWA', 'price' => '1750.00'],
            ['category' => 'STEPDOWN TRANSFORMER', 'model' => 'STEPDOWN-100V-500W', 'description' => '100V stepdown transformer 500W', 'brand' => 'TAMAGAWA', 'price' => '1890.00'],
            ['category' => 'STEPDOWN TRANSFORMER', 'model' => 'STEPDOWN-100V-750W', 'description' => '100V stepdown transformer 750W', 'brand' => 'TAMAGAWA', 'price' => '3100.00'],
            ['category' => 'STEPDOWN TRANSFORMER', 'model' => 'STEPDOWN-100V-1000W', 'description' => '100V stepdown transformer 1000W', 'brand' => 'TAMAGAWA', 'price' => '3990.00'],
            ['category' => 'STEPDOWN TRANSFORMER', 'model' => 'STEPDOWN-100V-1500W', 'description' => '100V stepdown transformer 1500W', 'brand' => 'TAMAGAWA', 'price' => '5500.00'],
            ['category' => 'STEPDOWN TRANSFORMER', 'model' => 'STEPDOWN-100V-2000W', 'description' => '100V stepdown transformer 2000W', 'brand' => 'TAMAGAWA', 'price' => '7500.00'],

            // BOOSTER TRANSFORMER
            ['category' => 'BOOSTER TRANSFORMER', 'model' => 'BOOSTER-50W', 'description' => 'Booster transformer 50W', 'brand' => 'TAMAGAWA', 'price' => '185.00'],
            ['category' => 'BOOSTER TRANSFORMER', 'model' => 'BOOSTER-100W', 'description' => 'Booster transformer 100W', 'brand' => 'TAMAGAWA', 'price' => '535.00'],
            ['category' => 'BOOSTER TRANSFORMER', 'model' => 'BOOSTER-150W', 'description' => 'Booster transformer 150W', 'brand' => 'TAMAGAWA', 'price' => '750.00'],
            ['category' => 'BOOSTER TRANSFORMER', 'model' => 'BOOSTER-200W', 'description' => 'Booster transformer 200W', 'brand' => 'TAMAGAWA', 'price' => '950.00'],

            // AUTOMATIC VOLTAGE REGULATOR
            ['category' => 'AUTOMATIC VOLTAGE REGULATOR', 'model' => 'SVR-1000 VA', 'description' => '500W AVR', 'brand' => 'HI-MARK', 'price' => '2190.00'],
            ['category' => 'AUTOMATIC VOLTAGE REGULATOR', 'model' => 'SVR-1500 VA', 'description' => '1500W AVR', 'brand' => 'HI-MARK', 'price' => '2790.00'],
            ['category' => 'AUTOMATIC VOLTAGE REGULATOR', 'model' => 'SVR-2000 VA', 'description' => '2000W AVR', 'brand' => 'HI-MARK', 'price' => '4490.00'],
            ['category' => 'AUTOMATIC VOLTAGE REGULATOR', 'model' => 'SVR-3000 VA', 'description' => '3000W AVR', 'brand' => 'HI-MARK', 'price' => '5290.00'],
            ['category' => 'AUTOMATIC VOLTAGE REGULATOR', 'model' => 'SVR-5000 VA SL', 'description' => '5000W AVR', 'brand' => 'HI-MARK', 'price' => '6950.00'],
            ['category' => 'AUTOMATIC VOLTAGE REGULATOR', 'model' => 'SVM-5KVA', 'description' => '5000W AVR', 'brand' => 'HI-MARK', 'price' => '9950.00'],
            ['category' => 'AUTOMATIC VOLTAGE REGULATOR', 'model' => 'SVR-10000 VA SL', 'description' => '10000W AVR', 'brand' => 'HI-MARK', 'price' => '13490.00'],
            ['category' => 'AUTOMATIC VOLTAGE REGULATOR', 'model' => 'SVM-10000 VA SL', 'description' => '10000W AVR', 'brand' => 'HI-MARK', 'price' => '16950.00'],
            ['category' => 'AUTOMATIC VOLTAGE REGULATOR', 'model' => 'SVM-15KVA', 'description' => '15000W AVR', 'brand' => 'HI-MARK', 'price' => '23900.00'],
            ['category' => 'AUTOMATIC VOLTAGE REGULATOR', 'model' => 'SVM-20KVA', 'description' => '20000W AVR', 'brand' => 'HI-MARK', 'price' => '34500.00'],

            // VARIABLE VOLTAGE REGULATOR
            ['category' => 'VARIABLE VOLTAGE REGULATOR', 'model' => 'STAVOL-1000W', 'description' => '1000W variable voltage regulator', 'brand' => 'STAVOL', 'price' => '3290.00'],
            ['category' => 'VARIABLE VOLTAGE REGULATOR', 'model' => 'STAVOL-2000W', 'description' => '2000W variable voltage regulator', 'brand' => 'STAVOL', 'price' => '4690.00'],
            ['category' => 'VARIABLE VOLTAGE REGULATOR', 'model' => 'STAVOL-3000W', 'description' => '3000W variable voltage regulator', 'brand' => 'STAVOL', 'price' => '5290.00'],

            // UNINTERRUPTED POWER SUPPLY
            ['category' => 'UNINTERRUPTED POWER SUPPLY', 'model' => 'UPS-500W-SAMWON', 'description' => '500W UPS', 'brand' => 'SAMWON', 'price' => '2890.00'],
            ['category' => 'UNINTERRUPTED POWER SUPPLY', 'model' => 'UPS-500W-POWEREE', 'description' => '500W UPS', 'brand' => 'POWEREE', 'price' => '2200.00'],

            // INSTRUMENTAL SPEAKERS
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'KPA-1230', 'description' => '12" 300W', 'brand' => 'KEVLER', 'price' => '1480.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'KPA-1550', 'description' => '15" 500W', 'brand' => 'KEVLER', 'price' => '2190.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'KPA-1550L', 'description' => '15" 500W with LED lights', 'brand' => 'KEVLER', 'price' => '5900.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'BNC-1240', 'description' => '12" 1200W', 'brand' => 'KEVLER', 'price' => '6200.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'JH-630', 'description' => '6" 300W', 'brand' => 'CROWN', 'price' => '720.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'JH-680', 'description' => '6" 800W', 'brand' => 'CROWN', 'price' => '1950.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'JH890', 'description' => '8" 900W', 'brand' => 'CROWN', 'price' => '1890.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'JH-860', 'description' => '8" 600W', 'brand' => 'CROWN', 'price' => '1960.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'JH-89', 'description' => '8" 900W', 'brand' => 'CROWN', 'price' => '2950.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'JH810', 'description' => '8" 1800W', 'brand' => 'CROWN', 'price' => '3390.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'JH-105', 'description' => '10" 500W', 'brand' => 'CROWN', 'price' => '1890.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'JH-108', 'description' => '10" 800W', 'brand' => 'CROWN', 'price' => '2290.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'JH-125', 'description' => '12" 500W', 'brand' => 'CROWN', 'price' => '3890.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'JH-157', 'description' => '15" 700W', 'brand' => 'CROWN', 'price' => '4590.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'BPA12-600', 'description' => '12" 600W', 'brand' => 'BROADWAY', 'price' => '1790.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'BW12-600', 'description' => '12" 600W', 'brand' => 'BROADWAY', 'price' => '1150.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'BWG12-600', 'description' => '12" 600W with grill', 'brand' => 'BROADWAY', 'price' => '1190.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'BW15-800', 'description' => '15" 800W', 'brand' => 'BROADWAY', 'price' => '1990.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'BWG15-800', 'description' => '15" 800W with grill', 'brand' => 'BROADWAY', 'price' => '2390.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'BWH-870', 'description' => '8" 700W', 'brand' => 'BROADWAY', 'price' => '1620.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'BWH-108', 'description' => '10" 800W', 'brand' => 'BROADWAY', 'price' => '2190.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'BWH-126', 'description' => '12" 600W', 'brand' => 'BROADWAY', 'price' => '2990.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'BWH-158', 'description' => '15" 800W', 'brand' => 'BROADWAY', 'price' => '3690.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'BWH-151K', 'description' => '15" 1000W', 'brand' => 'BROADWAY', 'price' => '6350.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'BWH-152K', 'description' => '15" 2000W', 'brand' => 'BROADWAY', 'price' => 'null'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'PA 6', 'description' => '6" 300W', 'brand' => 'ROCKSOUND', 'price' => '590.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'PA 8', 'description' => '8" 400W', 'brand' => 'ROCKSOUND', 'price' => '790.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'PA 10', 'description' => '10" 450W', 'brand' => 'ROCKSOUND', 'price' => '1150.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'PA 12', 'description' => '12" 500W', 'brand' => 'ROCKSOUND', 'price' => '1940.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'PA 15', 'description' => '15" 800W', 'brand' => 'ROCKSOUND', 'price' => '2290.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'NUC12-600', 'description' => '12" 600W', 'brand' => 'ATOMIC LIVE', 'price' => '2250.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'NUC15-600', 'description' => '15" 600W', 'brand' => 'ATOMIC LIVE', 'price' => '2240.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'STORM @7K', 'description' => '15" 700W', 'brand' => 'LIVE', 'price' => '2690.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'YD-166-35', 'description' => '4" 400W', 'brand' => 'CAPRIOLE', 'price' => '570.00'],
            ['category' => 'INSTRUMENTAL SPEAKERS', 'model' => 'WL-18', 'description' => '18" 1600W 100mm coil', 'brand' => 'JBL', 'price' => '8700.00'],

            // POWERED MIXERS
            ['category' => 'POWERED MIXERS', 'model' => 'POWERMIX-1000', 'description' => '550W 10 channel powered mixer', 'brand' => 'KEVLER', 'price' => '14900.00'],
            ['category' => 'POWERED MIXERS', 'model' => 'XPM-800', 'description' => '550W 8 channel powered mixer', 'brand' => 'KEVLER', 'price' => '21990.00'],
            ['category' => 'POWERED MIXERS', 'model' => 'XPM-1200', 'description' => '550W 14 channel powered mixer', 'brand' => 'KEVLER', 'price' => '23990.00'],
            ['category' => 'POWERED MIXERS', 'model' => 'PV-8D BT/USB', 'description' => '8 channel powered mixer', 'brand' => 'PEAVEY', 'price' => '10990.00'],
            ['category' => 'POWERED MIXERS', 'model' => 'PD4USBM', 'description' => '4 channel powered mixer', 'brand' => 'Y-CLASS A', 'price' => '6990.00'],
            ['category' => 'POWERED MIXERS', 'model' => 'PD6USBM', 'description' => '6 channel powered mixer', 'brand' => 'Y-CLASS A', 'price' => '7990.00'],
            ['category' => 'POWERED MIXERS', 'model' => 'PD12USBM', 'description' => '12 channel powered mixer', 'brand' => 'Y-CLASS A', 'price' => '10990.00'],

            // PROCESSORS
            ['category' => 'PROCESSORS', 'model' => 'PCS-510', 'description' => 'Power sequencer with circuit breaker, 8 socket +2 front 25A max output', 'brand' => 'KEVLER', 'price' => '5490.00'],
            ['category' => 'PROCESSORS', 'model' => 'PC901', 'description' => 'Power conditioner 8ch + front 15A output', 'brand' => 'KEVLER', 'price' => '4690.00'],
            ['category' => 'PROCESSORS', 'model' => '1231s', 'description' => 'Dual 31 band graphic EQ', 'brand' => 'KEVLER', 'price' => '7500.00'],
            ['category' => 'PROCESSORS', 'model' => '215SUB', 'description' => 'Dual 15 band graphic EQ with sub out', 'brand' => 'KEVLER', 'price' => '4290.00'],
            ['category' => 'PROCESSORS', 'model' => '231SUB', 'description' => 'Dual 31 band graphic EQ with sub out', 'brand' => 'KEVLER', 'price' => '6290.00'],
            ['category' => 'PROCESSORS', 'model' => '234s', 'description' => '2/3/4 way active crossover', 'brand' => 'KEVLER', 'price' => '4900.00'],
            ['category' => 'PROCESSORS', 'model' => '166s', 'description' => 'Dual channel compressor limiter gate', 'brand' => 'KEVLER', 'price' => 'null'],
            ['category' => 'PROCESSORS', 'model' => 'EQ215S', 'description' => '15 bands equalizer', 'brand' => 'TOSUNRA', 'price' => '1790.00'],
            ['category' => 'PROCESSORS', 'model' => '215s', 'description' => 'Dual 15 band graphic equalizer', 'brand' => 'DBX', 'price' => '2690.00'],
            ['category' => 'PROCESSORS', 'model' => '234s DBX', 'description' => '2/3/4 way active crossover', 'brand' => 'DBX', 'price' => '2690.00'],
            ['category' => 'PROCESSORS', 'model' => '234XL', 'description' => '2/3/4 way active crossover', 'brand' => 'TOSUNRA', 'price' => '1990.00'],
            ['category' => 'PROCESSORS', 'model' => 'TA-110', 'description' => 'Power sequencer', 'brand' => 'T-AUDIO', 'price' => '1690.00'],

            // WOOFER SPEAKERS
            ['category' => 'WOOFER SPEAKERS', 'model' => 'HW-6505', 'description' => '6" 80W', 'brand' => 'CROWN', 'price' => '380.00'],
            ['category' => 'WOOFER SPEAKERS', 'model' => 'HW-805', 'description' => '8" 50W', 'brand' => 'CROWN', 'price' => '390.00'],
            ['category' => 'WOOFER SPEAKERS', 'model' => 'HW-810', 'description' => '8" 100W', 'brand' => 'CROWN', 'price' => '590.00'],
            ['category' => 'WOOFER SPEAKERS', 'model' => 'HW-1010', 'description' => '8" 100W', 'brand' => 'CROWN', 'price' => '890.00'],
            ['category' => 'WOOFER SPEAKERS', 'model' => 'HW-1230', 'description' => '12" 300W', 'brand' => 'CROWN', 'price' => '1390.00'],
            ['category' => 'WOOFER SPEAKERS', 'model' => 'HW-1250', 'description' => '15" 500W', 'brand' => 'CROWN', 'price' => '1790.00'],
            ['category' => 'WOOFER SPEAKERS', 'model' => 'HW-1508', 'description' => '15" 800W', 'brand' => 'CROWN', 'price' => '3990.00'],
            ['category' => 'WOOFER SPEAKERS', 'model' => 'GT-12V', 'description' => '12" 300W', 'brand' => 'KEVLER', 'price' => '1690.00'],
            ['category' => 'WOOFER SPEAKERS', 'model' => 'GT-15V', 'description' => '15" 500W', 'brand' => 'KEVLER', 'price' => '2590.00'],
            ['category' => 'WOOFER SPEAKERS', 'model' => 'YD-166-39', 'description' => '6.5" 300W', 'brand' => 'CAPRIOLE', 'price' => '590.00'],
            ['category' => 'WOOFER SPEAKERS', 'model' => 'YD250-43B', 'description' => '10" 450W', 'brand' => 'CAPRIOLE', 'price' => '1490.00'],
            ['category' => 'WOOFER SPEAKERS', 'model' => 'HW-4200', 'description' => '4" 200W', 'brand' => 'CAPRIOLE', 'price' => '450.00'],
            ['category' => 'WOOFER SPEAKERS', 'model' => 'HW-5250', 'description' => '5.5" 250W', 'brand' => 'CAPRIOLE', 'price' => '490.00'],
            ['category' => 'WOOFER SPEAKERS', 'model' => 'HW-6300', 'description' => '6" 300W', 'brand' => 'CAPRIOLE', 'price' => '590.00'],

            // SUB-WOOFER SPEAKERS
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'PRO-SW-825', 'description' => '8" 250W', 'brand' => 'CROWN', 'price' => '980.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'PRO-SW-103M', 'description' => '10" 300W', 'brand' => 'CROWN', 'price' => '1190.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'PRO-SW-104M', 'description' => '10" 400W', 'brand' => 'CROWN', 'price' => '1390.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'PRO-SW-1236', 'description' => '12" 360W', 'brand' => 'CROWN', 'price' => '1890.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'PRO-SW-1540', 'description' => '15" 400W', 'brand' => 'CROWN', 'price' => '2890.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'PRO-SW-1545', 'description' => '15" 450W', 'brand' => 'CROWN', 'price' => '3550.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'TS-SW2002DZ', 'description' => '8" 700W', 'brand' => 'PIONEER', 'price' => '1390.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'TS-W2547', 'description' => '10" 1000W', 'brand' => 'PIONEER', 'price' => '2890.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'TS-304R', 'description' => '10" 1200W', 'brand' => 'PIONEER', 'price' => '1490.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'AKW3000', 'description' => '12" 300W', 'brand' => 'AUDIOLINE', 'price' => '1485.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'SUB15M', 'description' => '15" 500W', 'brand' => 'AUDIOLINE', 'price' => '2190.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'KW3000M', 'description' => '12" 300W', 'brand' => 'KONZERT', 'price' => '1790.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'KW-3000', 'description' => '12" 300W', 'brand' => 'KONZERT', 'price' => '1490.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'STAGE 12', 'description' => '12" 300W', 'brand' => 'JOSON', 'price' => '3990.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'THUNDER', 'description' => '12" 500W', 'brand' => 'JOSON', 'price' => '2750.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => '12DM-600', 'description' => '12" 600W dual magnet waterproof', 'brand' => 'KEVLER', 'price' => '3750.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => '15DM-800', 'description' => '15" 800W dual magnet waterproof', 'brand' => 'KEVLER', 'price' => '4950.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'SDM-1840', 'description' => '18" 1400W dual magnet subwoofer', 'brand' => 'KEVLER', 'price' => '8600.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'RC-18-1200', 'description' => '18" 1200W', 'brand' => 'KEVLER', 'price' => '6600.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'TX-SUB4', 'description' => '4" 150W', 'brand' => 'CAPRIOLE', 'price' => '320.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'TX-SUB5', 'description' => '5" 300W', 'brand' => 'CAPRIOLE', 'price' => '420.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'TX-SUB6', 'description' => '6.5" 350W', 'brand' => 'CAPRIOLE', 'price' => '490.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'BASS-101', 'description' => '10" 1000W 4ohm', 'brand' => 'TOSUNRA', 'price' => '820.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'BASS-121', 'description' => '12" 2000W 4ohm', 'brand' => 'TOSUNRA', 'price' => '1150.00'],
            ['category' => 'SUB-WOOFER SPEAKERS', 'model' => 'SW-15P', 'description' => '15" 3000W 4ohm', 'brand' => 'TOSUNRA', 'price' => '2250.00'],

            // GUITAR AMP / BASS AMP
            ['category' => 'GUITAR AMP / BASS AMP', 'model' => 'TG-30W', 'description' => 'Guitar amplifier', 'brand' => 'SNIGER', 'price' => '3990.00'],
            ['category' => 'GUITAR AMP / BASS AMP', 'model' => 'TG-40W', 'description' => 'Guitar amplifier', 'brand' => 'SNIGER', 'price' => '5790.00'],
            ['category' => 'GUITAR AMP / BASS AMP', 'model' => 'TG-60W', 'description' => 'Guitar amplifier', 'brand' => 'SNIGER', 'price' => '8790.00'],

            // SOUNDBAR
            ['category' => 'SOUNDBAR', 'model' => 'SBR-5000', 'description' => '500W soundbar speaker', 'brand' => 'KEVLER', 'price' => '5900.00'],

            // COLUMN ARRAY SPEAKER SYSTEM
            ['category' => 'COLUMN ARRAY SPEAKER SYSTEM', 'model' => 'A9', 'description' => '15" 500W active subwoofer + 300W column speaker, 6pcs 3.5"', 'brand' => 'KEVLER', 'price' => '35000.00'],
            ['category' => 'COLUMN ARRAY SPEAKER SYSTEM', 'model' => 'SW-ProGo8', 'description' => null, 'brand' => 'SAMWON', 'price' => '18900.00'],
            ['category' => 'COLUMN ARRAY SPEAKER SYSTEM', 'model' => 'SW-ProGo10', 'description' => null, 'brand' => 'SAMWON', 'price' => 'null'],

            // MIDRANGE
            ['category' => 'MIDRANGE', 'model' => 'BM-100M', 'description' => '4" 100W', 'brand' => 'BROADWAY', 'price' => '285.00'],
            ['category' => 'MIDRANGE', 'model' => 'BM-150M', 'description' => '5" 150W', 'brand' => 'BROADWAY', 'price' => '320.00'],
            ['category' => 'MIDRANGE', 'model' => 'SG-4M', 'description' => '4" 120W', 'brand' => 'KONZERT', 'price' => '245.00'],
            ['category' => 'MIDRANGE', 'model' => 'SG-5M', 'description' => '5" 150W', 'brand' => 'KONZERT', 'price' => '320.00'],
            ['category' => 'MIDRANGE', 'model' => 'GT-4M', 'description' => '4" 120W', 'brand' => 'KEVLER', 'price' => '395.00'],
            ['category' => 'MIDRANGE', 'model' => 'GT-5M', 'description' => '5" 150W', 'brand' => 'KEVLER', 'price' => '485.00'],

            // TWEETER
            ['category' => 'TWEETER', 'model' => 'SG-3T', 'description' => null, 'brand' => 'KONZERT', 'price' => '185.00'],
            ['category' => 'TWEETER', 'model' => 'KMDT-100', 'description' => null, 'brand' => 'KONZERT', 'price' => '220.00'],
            ['category' => 'TWEETER', 'model' => 'PRO-KMDT100', 'description' => null, 'brand' => 'KONZERT', 'price' => '220.00'],
            ['category' => 'TWEETER', 'model' => 'TS-120', 'description' => null, 'brand' => 'PIONEER', 'price' => '220.00'],
            ['category' => 'TWEETER', 'model' => 'YDQZ100-1', 'description' => '4" 100W', 'brand' => 'CAPRIOLE', 'price' => '265.00'],
            ['category' => 'TWEETER', 'model' => 'CATW25-02G', 'description' => '4" 700W', 'brand' => 'CAPRIOLE', 'price' => '390.00'],
            ['category' => 'TWEETER', 'model' => 'CATW25-03G', 'description' => null, 'brand' => 'CAPRIOLE', 'price' => '390.00'],
            ['category' => 'TWEETER', 'model' => 'HD-004', 'description' => null, 'brand' => 'CAPRIOLE', 'price' => '145.00'],
            ['category' => 'TWEETER', 'model' => 'PV-44XT', 'description' => 'Peavey bolt on tweeter', 'brand' => 'PEAVEY', 'price' => '4200.00'],
            ['category' => 'TWEETER', 'model' => 'SB-06', 'description' => 'Titanium tweeter', 'brand' => 'ROCKSOUND', 'price' => '450.00'],
            ['category' => 'TWEETER', 'model' => 'SB-08', 'description' => 'Titanium tweeter', 'brand' => 'ROCKSOUND', 'price' => '890.00'],
            ['category' => 'TWEETER', 'model' => 'SR-34', 'description' => 'Compression driver unit tweeter', 'brand' => 'ROCKSOUND', 'price' => '690.00'],
            ['category' => 'TWEETER', 'model' => 'SR-44', 'description' => 'Compression driver unit tweeter', 'brand' => 'ROCKSOUND', 'price' => '890.00'],
            ['category' => 'TWEETER', 'model' => 'SR-51', 'description' => 'Compression driver unit tweeter', 'brand' => 'ROCKSOUND', 'price' => '1490.00'],
            ['category' => 'TWEETER', 'model' => 'HT-104', 'description' => '10" x 4" 150W', 'brand' => 'CROWN', 'price' => '550.00'],
            ['category' => 'TWEETER', 'model' => 'HT-38', 'description' => '3" x 8" 150W', 'brand' => 'CROWN', 'price' => '390.00'],
            ['category' => 'TWEETER', 'model' => 'CY-300', 'description' => '300W compression driver unit', 'brand' => 'CROWN', 'price' => '1290.00'],
            ['category' => 'TWEETER', 'model' => 'CY-500', 'description' => '500W compression driver unit', 'brand' => 'CROWN', 'price' => '2790.00'],
            ['category' => 'TWEETER', 'model' => 'BCS-300', 'description' => '300W compression driver unit tweeter', 'brand' => 'BROADWAY', 'price' => '780.00'],
            ['category' => 'TWEETER', 'model' => 'BCS-400', 'description' => '400W compression driver unit tweeter', 'brand' => 'BROADWAY', 'price' => '1490.00'],
            ['category' => 'TWEETER', 'model' => 'HDC-1000', 'description' => '1000W compression driver unit tweeter bolt type', 'brand' => 'BROADWAY', 'price' => '3990.00'],
            ['category' => 'TWEETER', 'model' => 'GT-100S', 'description' => '100W dome tweeter', 'brand' => 'KEVLER', 'price' => '375.00'],
            ['category' => 'TWEETER', 'model' => 'T-3', 'description' => '300W compression driver unit tweeter', 'brand' => 'KEVLER', 'price' => '1150.00'],
            ['category' => 'TWEETER', 'model' => 'T-5', 'description' => '500W compression driver unit tweeter', 'brand' => 'KEVLER', 'price' => '1650.00'],
            ['category' => 'TWEETER', 'model' => 'T-7', 'description' => '700W compression driver unit tweeter', 'brand' => 'KEVLER', 'price' => '2450.00'],
            ['category' => 'TWEETER', 'model' => 'T-1000', 'description' => '1000W compression driver unit tweeter', 'brand' => 'KEVLER', 'price' => '2890.00'],
            ['category' => 'TWEETER', 'model' => 'NT-1000', 'description' => '1000W neodymium compression driver tweeter', 'brand' => 'KEVLER', 'price' => '9200.00'],
            ['category' => 'TWEETER', 'model' => 'NT-25', 'description' => '250W neodymium compression driver unit tweeter', 'brand' => 'KEVLER', 'price' => '3900.00'],
            ['category' => 'TWEETER', 'model' => 'NT-38', 'description' => '3" x 8" 150W horn tweeter', 'brand' => 'KEVLER', 'price' => '450.00'],
            ['category' => 'TWEETER', 'model' => 'DST-34', 'description' => '200W compression driver unit tweeter', 'brand' => 'KEVLER', 'price' => '890.00'],
            ['category' => 'TWEETER', 'model' => 'DST-44', 'description' => '300W compression driver unit tweeter', 'brand' => 'KEVLER', 'price' => '1190.00'],
            ['category' => 'TWEETER', 'model' => 'DST-50', 'description' => '500W compression driver unit tweeter', 'brand' => 'KEVLER', 'price' => '1790.00'],
            ['category' => 'TWEETER', 'model' => 'DST-75', 'description' => '700W compression driver unit tweeter', 'brand' => 'KEVLER', 'price' => '2790.00'],
            ['category' => 'TWEETER', 'model' => 'T230-2', 'description' => '2" tweeter', 'brand' => 'EXPRESS', 'price' => '38.00'],
            ['category' => 'TWEETER', 'model' => '90-35', 'description' => 'Tweeter 200W 4ohm', 'brand' => 'TOSUNRA', 'price' => '650.00'],
            ['category' => 'TWEETER', 'model' => '115-44', 'description' => 'Tweeter 400W 4ohm', 'brand' => 'TOSUNRA', 'price' => '735.00'],

            // TV SPEAKERS
            ['category' => 'TV SPEAKERS', 'model' => 'YDN85', 'description' => '3" square TV speaker', 'brand' => null, 'price' => '95.00'],
            ['category' => 'TV SPEAKERS', 'model' => 'YD155 30', 'description' => '4x1 TV speaker', 'brand' => null, 'price' => '95.00'],

            // MICROPHONES
            ['category' => 'MICROPHONES', 'model' => 'PM-830', 'description' => 'Super cardioid microphone with 10m cable', 'brand' => 'KEVLER', 'price' => '780.00'],
            ['category' => 'MICROPHONES', 'model' => 'DM-750', 'description' => 'Super cardioid microphone with 10m cable', 'brand' => 'KEVLER', 'price' => '890.00'],
            ['category' => 'MICROPHONES', 'model' => 'DM-950', 'description' => 'Super cardioid microphone with 10m cable', 'brand' => 'KEVLER', 'price' => '1200.00'],
            ['category' => 'MICROPHONES', 'model' => 'DM-1200', 'description' => 'Super cardioid microphone with 10m cable', 'brand' => 'KEVLER', 'price' => '1500.00'],
            ['category' => 'MICROPHONES', 'model' => 'DM-1400', 'description' => 'Super cardioid microphone with 10m magnetized cable', 'brand' => 'KEVLER', 'price' => '1690.00'],
            ['category' => 'MICROPHONES', 'model' => 'GS-55', 'description' => 'Super cardioid microphone with 10m cable', 'brand' => 'CAROL', 'price' => '750.00'],
            ['category' => 'MICROPHONES', 'model' => 'BE-20', 'description' => 'Super cardioid microphone with 10m cable', 'brand' => 'BEHRINGER', 'price' => '1500.00'],
            ['category' => 'MICROPHONES', 'model' => 'SV-100', 'description' => 'Super cardioid microphone with 10m cable', 'brand' => 'SHURE', 'price' => '2700.00'],
            ['category' => 'MICROPHONES', 'model' => 'SV-200', 'description' => 'Super cardioid microphone with 10m cable', 'brand' => 'SHURE', 'price' => '3200.00'],
            ['category' => 'MICROPHONES', 'model' => 'PG-48', 'description' => 'Super cardioid microphone with 10m cable', 'brand' => 'SHURE', 'price' => '5290.00'],
            ['category' => 'MICROPHONES', 'model' => 'PG-58', 'description' => 'Super cardioid microphone with 10m cable', 'brand' => 'SHURE', 'price' => '5890.00'],
            ['category' => 'MICROPHONES', 'model' => 'SM-58', 'description' => 'Super cardioid microphone without cable', 'brand' => 'SHURE', 'price' => '9900.00'],
            ['category' => 'MICROPHONES', 'model' => 'SM-88A', 'description' => 'Super cardioid microphone without cable', 'brand' => 'SHURE', 'price' => '1500.00'],
            ['category' => 'MICROPHONES', 'model' => 'SM-78A', 'description' => 'Super cardioid microphone without cable', 'brand' => 'SHURE', 'price' => 'null'],
            ['category' => 'MICROPHONES', 'model' => 'TA-3000', 'description' => 'Super cardioid microphone without cable', 'brand' => 'T-AUDIO', 'price' => '290.00'],
            ['category' => 'MICROPHONES', 'model' => 'MIC-1000', 'description' => 'Super cardioid microphone without cable', 'brand' => 'BROADWAY', 'price' => '390.00'],
            ['category' => 'MICROPHONES', 'model' => 'MT-ULAP', 'description' => 'Super cardioid microphone without cable', 'brand' => 'JOSON', 'price' => '1950.00'],
            ['category' => 'MICROPHONES', 'model' => 'MT TAAI', 'description' => 'Super cardioid microphone without cable', 'brand' => 'JOSON', 'price' => '1950.00'],
            ['category' => 'MICROPHONES', 'model' => 'VC-100', 'description' => 'Volume control', 'brand' => 'KEVLER', 'price' => '1390.00'],
            ['category' => 'MICROPHONES', 'model' => 'ADT-2.0C', 'description' => 'Wired to wireless microphone adapter', 'brand' => 'KEVLER', 'price' => '1950.00'],
            ['category' => 'MICROPHONES', 'model' => 'LAV-100', 'description' => 'Single portable lavalier mic', 'brand' => 'KEVLER', 'price' => '2100.00'],
            ['category' => 'MICROPHONES', 'model' => 'UHM-100', 'description' => 'Single portable headphone mic', 'brand' => 'KEVLER', 'price' => '1950.00'],
            ['category' => 'MICROPHONES', 'model' => 'CM-100UR', 'description' => 'Paging microphone', 'brand' => 'KEVLER', 'price' => '3490.00'],
            ['category' => 'MICROPHONES', 'model' => 'AKM-58', 'description' => 'Dual portable handheld mic', 'brand' => 'KEVLER', 'price' => '3850.00'],
            ['category' => 'MICROPHONES', 'model' => 'PM-101', 'description' => 'Dual channel UHF mic', 'brand' => 'KEVLER', 'price' => '5190.00'],
            ['category' => 'MICROPHONES', 'model' => 'UM-200S', 'description' => 'Dual UHF wireless with li-ion battery charger', 'brand' => 'KEVLER', 'price' => '7490.00'],
            ['category' => 'MICROPHONES', 'model' => 'UM-500', 'description' => 'Dual UHF wireless with li-ion battery charger', 'brand' => 'KEVLER', 'price' => '8950.00'],
            ['category' => 'MICROPHONES', 'model' => 'UMC-1000', 'description' => 'Quad UHF wireless mic with li-ion battery charger', 'brand' => 'KEVLER', 'price' => '15900.00'],
            ['category' => 'MICROPHONES', 'model' => 'RCM-77', 'description' => 'Dual UHF portable handheld mic', 'brand' => 'KEVLER', 'price' => '5750.00'],
            ['category' => 'MICROPHONES', 'model' => 'MR-250H', 'description' => 'Dual UHF handheld mic', 'brand' => 'KEVLER', 'price' => '7850.00'],
            ['category' => 'MICROPHONES', 'model' => 'URX-2H', 'description' => 'Dual UHF handheld mic', 'brand' => 'KEVLER', 'price' => '2250.00'],
            ['category' => 'MICROPHONES', 'model' => 'URX-2B', 'description' => 'Dual UHF lapel/headworn mic', 'brand' => 'KEVLER', 'price' => '2750.00'],
            ['category' => 'MICROPHONES', 'model' => 'UZ700', 'description' => 'Dual UHF handheld mic', 'brand' => 'KEVLER', 'price' => '4200.00'],
            ['category' => 'MICROPHONES', 'model' => 'ATC-2000', 'description' => 'Handheld microphone dual', 'brand' => 'KEVLER', 'price' => '18500.00'],
            ['category' => 'MICROPHONES', 'model' => 'TDX-2000B', 'description' => 'Lapel microphone dual', 'brand' => 'KEVLER', 'price' => '18500.00'],
            ['category' => 'MICROPHONES', 'model' => 'YM-288', 'description' => 'Dual UHF handheld mic', 'brand' => 'SAMWON', 'price' => '1790.00'],
            ['category' => 'MICROPHONES', 'model' => 'SKM9000', 'description' => 'Dual UHF handheld mic', 'brand' => 'SENNHEISER', 'price' => '7900.00'],
            ['category' => 'MICROPHONES', 'model' => 'TA-800', 'description' => 'Dual UHF handheld mic', 'brand' => 'T-AUDIO', 'price' => '6690.00'],
            ['category' => 'MICROPHONES', 'model' => 'TA-90V', 'description' => 'Dual UHF handheld mic', 'brand' => 'T-AUDIO', 'price' => '8990.00'],
            ['category' => 'MICROPHONES', 'model' => 'TA-1000', 'description' => 'Quad UHF handheld mic', 'brand' => 'T-AUDIO', 'price' => '13990.00'],
            ['category' => 'MICROPHONES', 'model' => 'TA-200 PRO', 'description' => 'Dual UHF wireless mic', 'brand' => 'T-AUDIO', 'price' => '11990.00'],
            ['category' => 'MICROPHONES', 'model' => 'BLX-C8', 'description' => 'Dual wireless mic', 'brand' => 'SHURE', 'price' => '3990.00'],

            // MIXERS
            ['category' => 'MIXERS', 'model' => 'SMX-6BT', 'description' => '6 channel mixer (knob)', 'brand' => 'KEVLER', 'price' => '5990.00'],
            ['category' => 'MIXERS', 'model' => 'SMX-8BT', 'description' => '8 channel mixer (knob)', 'brand' => 'KEVLER', 'price' => '6990.00'],
            ['category' => 'MIXERS', 'model' => 'MIX-8BT', 'description' => '8 channel mixer fader', 'brand' => 'KEVLER', 'price' => '10990.00'],
            ['category' => 'MIXERS', 'model' => 'MIX-12BT', 'description' => '12 channel mixer', 'brand' => 'KEVLER', 'price' => '11990.00'],
            ['category' => 'MIXERS', 'model' => 'MIX-16BT', 'description' => '16 channel mixer', 'brand' => 'KEVLER', 'price' => '14500.00'],
            ['category' => 'MIXERS', 'model' => 'MIX-20BT', 'description' => '20 channel mixer', 'brand' => 'KEVLER', 'price' => '16990.00'],
            ['category' => 'MIXERS', 'model' => 'MATE-6', 'description' => '6 channel mixer 2 aux with phantom', 'brand' => 'KEVLER', 'price' => '6500.00'],
            ['category' => 'MIXERS', 'model' => 'MATE-8', 'description' => '8 channel mixer 2 aux with phantom', 'brand' => 'KEVLER', 'price' => '7990.00'],
            ['category' => 'MIXERS', 'model' => 'STUDIO-16', 'description' => '16 channel 12 mic line with 4 aux', 'brand' => 'KEVLER', 'price' => '18500.00'],
            ['category' => 'MIXERS', 'model' => 'STUDIO24', 'description' => '24 channel 16 mic line with 4 aux', 'brand' => 'KEVLER', 'price' => '27990.00'],
            ['category' => 'MIXERS', 'model' => 'STUDIO-32', 'description' => '32 channel 24 mic line with 4 aux', 'brand' => 'KEVLER', 'price' => '33900.00'],
            ['category' => 'MIXERS', 'model' => 'BF-4', 'description' => '4 channel mixer', 'brand' => 'Y-CLASS A', 'price' => '2650.00'],
            ['category' => 'MIXERS', 'model' => 'BF-7', 'description' => '7 channel mixer', 'brand' => 'Y-CLASS A', 'price' => '3750.00'],
            ['category' => 'MIXERS', 'model' => 'F4', 'description' => '7 channel mixer', 'brand' => 'TRIDENT', 'price' => '2500.00'],
            ['category' => 'MIXERS', 'model' => 'F7', 'description' => '7 channel mixer orange box', 'brand' => 'SOUNDROCK', 'price' => '2650.00'],
            ['category' => 'MIXERS', 'model' => 'XV-4', 'description' => '4 channel mixer', 'brand' => 'NEXO', 'price' => '3750.00'],
            ['category' => 'MIXERS', 'model' => 'XV-7', 'description' => '7 channel mixer', 'brand' => 'NEXO', 'price' => '4750.00'],
            ['category' => 'MIXERS', 'model' => 'YM-60', 'description' => '6 channel mixer', 'brand' => 'Y-CLASS A', 'price' => '6990.00'],
            ['category' => 'MIXERS', 'model' => 'YM-80', 'description' => '8 channel mixer', 'brand' => 'Y-CLASS A', 'price' => '7990.00'],
            ['category' => 'MIXERS', 'model' => 'YM-12', 'description' => '12 channel mixer', 'brand' => 'Y-CLASS A', 'price' => '9900.00'],
            ['category' => 'MIXERS', 'model' => 'YV-60', 'description' => '6 channel mixer', 'brand' => 'Y-CLASS A', 'price' => '6990.00'],
            ['category' => 'MIXERS', 'model' => 'XV-80', 'description' => '8 channel mixer', 'brand' => 'Y-CLASS A', 'price' => '7900.00'],
            ['category' => 'MIXERS', 'model' => 'SIGNATURE 22', 'description' => '22 channel mixer soundraft class A', 'brand' => 'SOUNDCRAFT', 'price' => '27990.00'],
            ['category' => 'MIXERS', 'model' => 'MIX-1202USB/BT', 'description' => '12 channel mixer', 'brand' => 'MICKLE', 'price' => '8990.00'],
            ['category' => 'MIXERS', 'model' => 'PV-6 USB', 'description' => '6 channel mixer', 'brand' => 'SURAJ', 'price' => '6990.00'],
            ['category' => 'MIXERS', 'model' => 'NX-8PRO', 'description' => '8 channel mixer', 'brand' => 'SR', 'price' => '13950.00'],
            ['category' => 'MIXERS', 'model' => 'NX-12PRO', 'description' => '12 channel mixer', 'brand' => 'SR', 'price' => '15950.00'],
            ['category' => 'MIXERS', 'model' => 'XV120', 'description' => '12 channel mixer', 'brand' => 'SR', 'price' => '7900.00'],
            ['category' => 'MIXERS', 'model' => 'SPIDER-4PLUS', 'description' => '4 channel mixer', 'brand' => 'JOSON', 'price' => '5900.00'],
            ['category' => 'MIXERS', 'model' => 'SPIDER-6PLUS', 'description' => '6 channel mixer', 'brand' => 'JOSON', 'price' => '6600.00'],
            ['category' => 'MIXERS', 'model' => 'SPIDER-8PLUS', 'description' => '8 channel mixer', 'brand' => 'JOSON', 'price' => '7300.00'],
            ['category' => 'MIXERS', 'model' => 'FX-400', 'description' => '4 channel mixer', 'brand' => 'STELLAR', 'price' => '4600.00'],
            ['category' => 'MIXERS', 'model' => 'FX-600', 'description' => '6 channel mixer', 'brand' => 'STELLAR', 'price' => '5500.00'],
            ['category' => 'MIXERS', 'model' => 'FX-800', 'description' => '8 channel mixer', 'brand' => 'STELLAR', 'price' => '6900.00'],

            // SUB-WOOFER BAFFLES
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'BW-8', 'description' => '8" 150W active subwoofer', 'brand' => 'CROWN', 'price' => '6900.00'],
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'BW-10', 'description' => '10" 300W active subwoofer', 'brand' => 'CROWN', 'price' => '7900.00'],
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'BW-12', 'description' => '12" 350W active subwoofer', 'brand' => 'CROWN', 'price' => '8900.00'],
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'BF-12SW', 'description' => '12" 500W passive subwoofer', 'brand' => 'CROWN', 'price' => '7990.00'],
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'BF-15SW', 'description' => '15" 700W passive subwoofer', 'brand' => 'CROWN', 'price' => '10990.00'],
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'BF-18SW', 'description' => '18" 800-1000W passive subwoofer', 'brand' => 'CROWN', 'price' => '17990.00'],
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'BF-12SA', 'description' => '12" 350W active subwoofer', 'brand' => 'CROWN', 'price' => '10990.00'],
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'BF-15SA', 'description' => '15" 400W active subwoofer', 'brand' => 'CROWN', 'price' => '16500.00'],
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'BF-18SA', 'description' => '18" 1200-1500W active subwoofer', 'brand' => 'CROWN', 'price' => '23000.00'],
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'KRX-615SA', 'description' => '15" 600W active subwoofer', 'brand' => 'KEVLER', 'price' => '23000.00'],
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'KRX-618SA', 'description' => '18" 800W active subwoofer', 'brand' => 'KEVLER', 'price' => '26000.00'],
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'ZLX-15SD', 'description' => '15" 800W active subwoofer', 'brand' => 'KEVLER', 'price' => '25000.00'],
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'ZLX-18SD', 'description' => '18" 1200W active subwoofer', 'brand' => 'KEVLER', 'price' => '35000.00'],
            ['category' => 'SUB-WOOFER BAFFLES', 'model' => 'SRX-718SM', 'description' => '18" passive subwoofer', 'brand' => 'BM AUDIO', 'price' => '24500.00'],

            // KARAOKE PLAYERS
            ['category' => 'KARAOKE PLAYERS', 'model' => 'SUPREMO', 'description' => '1TB hard disk with 18k songs and OPM, WiFi ready', 'brand' => 'TJ MEDIA', 'price' => '32295.00'],
            ['category' => 'KARAOKE PLAYERS', 'model' => 'TKR-305P', 'description' => '1TB hard disk with 20k songs HD background', 'brand' => 'TJ MEDIA', 'price' => '24950.00'],
            ['category' => 'KARAOKE PLAYERS', 'model' => 'MAESTRO II', 'description' => '32GB SD card 15k songs', 'brand' => 'TJ MEDIA', 'price' => '12995.00'],
            ['category' => 'KARAOKE PLAYERS', 'model' => 'KEYBOARD', 'description' => null, 'brand' => 'TJ MEDIA', 'price' => '2750.00'],
            ['category' => 'KARAOKE PLAYERS', 'model' => 'REMOTE', 'description' => null, 'brand' => 'TJ MEDIA', 'price' => '950.00'],
            ['category' => 'KARAOKE PLAYERS', 'model' => 'SONGBOOK', 'description' => null, 'brand' => 'TJ MEDIA', 'price' => '1500.00'],

            // PLATINUM
            ['category' => 'PLATINUM', 'model' => 'JUNIOR LITE', 'description' => null, 'brand' => null, 'price' => '2990.00'],
            ['category' => 'PLATINUM', 'model' => 'JUNIOR 2', 'description' => null, 'brand' => null, 'price' => '3650.00'],

            // WALL & CEILING SPEAKERS
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'HF-805CT', 'description' => '8" 50W ceiling speaker', 'brand' => 'CROWN', 'price' => '990.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'HT-802CT', 'description' => '8" 20W ceiling speaker', 'brand' => 'CROWN', 'price' => '890.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'HF-602CT', 'description' => '6" 10W ceiling speaker', 'brand' => 'CROWN', 'price' => '790.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'CSL-805', 'description' => '8" 10W ceiling speaker', 'brand' => 'KEVLER', 'price' => '895.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'CSL-605', 'description' => '6" 5W ceiling speaker', 'brand' => 'KEVLER', 'price' => '790.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'CSL-623', 'description' => '6" ceiling speaker with back cover multi tap', 'brand' => 'KEVLER', 'price' => '1490.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'LS-525', 'description' => 'Landscape garden speaker', 'brand' => 'KEVLER', 'price' => '11500.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'CLM-301TB', 'description' => '3" x 4 dome tweeter column speaker 60W black', 'brand' => 'KEVLER', 'price' => '16500.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'CLM-301TW', 'description' => '3" x 4 dome tweeter column speaker 60W white', 'brand' => 'KEVLER', 'price' => '16500.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'CLM-401TB', 'description' => '4" x 4 dome tweeter column speaker 120W black', 'brand' => 'KEVLER', 'price' => '15500.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'CLM-401TW', 'description' => '4" x 4 dome tweeter column speaker 120W white', 'brand' => 'KEVLER', 'price' => '15000.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'CLM-601TB', 'description' => '4" x 6 dome tweeter column speaker 150W black', 'brand' => 'KEVLER', 'price' => '19000.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'CLM-601TW', 'description' => '4" x 6 dome tweeter column speaker 150W white', 'brand' => 'KEVLER', 'price' => '19000.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'AWS-102TB', 'description' => '4" all weather speaker waterproof 100W black', 'brand' => 'KEVLER', 'price' => '8500.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'AWS-104TW', 'description' => '4" all weather speaker waterproof 100W white', 'brand' => 'KEVLER', 'price' => '8500.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'AWS-106TB', 'description' => '6" all weather speaker waterproof 100W black', 'brand' => 'KEVLER', 'price' => '14900.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'AWS-106TW', 'description' => '6" all weather speaker waterproof 100W white', 'brand' => 'KEVLER', 'price' => '14900.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'AWS-8S', 'description' => '8" all weather speaker waterproof 200W', 'brand' => 'KEVLER', 'price' => '13500.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'AWS-12H', 'description' => '12" all weather speaker waterproof 300W', 'brand' => 'KEVLER', 'price' => '19900.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'WS-5T', 'description' => '5" wall mount speaker 30W black', 'brand' => 'KEVLER', 'price' => '2750.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'WS5TW', 'description' => '5" wall mount speaker 30W white', 'brand' => 'KEVLER', 'price' => '2750.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'WS-6T', 'description' => '6.5" wall mount speaker black', 'brand' => 'KEVLER', 'price' => '3250.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'WS-6TW', 'description' => '6.5" wall mount speaker 30W white', 'brand' => 'KEVLER', 'price' => '3250.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'WS-60ST', 'description' => '6.5" wall mount speaker 40W black', 'brand' => 'KEVLER', 'price' => '8500.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'WSL-62T', 'description' => '6.5" 2-way wall mount speaker 10W', 'brand' => 'KEVLER', 'price' => '1650.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'ST-108', 'description' => 'Ceiling speaker', 'brand' => 'AUDIOLINE', 'price' => '750.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'F.LHY6.5D', 'description' => '6.5" wall speaker', 'brand' => 'AUDIOLINE', 'price' => '4950.00'],
            ['category' => 'WALL & CEILING SPEAKERS', 'model' => 'F.LHY5J', 'description' => '5" wall speaker (curve type)', 'brand' => 'AUDIOLINE', 'price' => '2500.00'],

            // HORN SPEAKERS
            ['category' => 'HORN SPEAKERS', 'model' => 'HF-10', 'description' => '10" aluminum horn speaker multi tap 3W-30W', 'brand' => 'KEVLER', 'price' => '4650.00'],
            ['category' => 'HORN SPEAKERS', 'model' => 'HF-20', 'description' => '20" aluminum horn speaker multi tap 50W', 'brand' => 'KEVLER', 'price' => '4590.00'],
            ['category' => 'HORN SPEAKERS', 'model' => 'HF-203', 'description' => '20" aluminum horn speaker multi tap 70W', 'brand' => 'KEVLER', 'price' => '4890.00'],
            ['category' => 'HORN SPEAKERS', 'model' => 'HS-30S', 'description' => '10" aluminum horn speaker multi tap 30W', 'brand' => 'KEVLER', 'price' => '3390.00'],
            ['category' => 'HORN SPEAKERS', 'model' => 'HS-50S', 'description' => '13" aluminum horn speaker multi tap 50W', 'brand' => 'KEVLER', 'price' => '4450.00'],
            ['category' => 'HORN SPEAKERS', 'model' => 'HS-65S', 'description' => '15" x 12" horn speaker multi tap 60W', 'brand' => 'KEVLER', 'price' => '6290.00'],
            ['category' => 'HORN SPEAKERS', 'model' => 'HS-14', 'description' => '6.5" horn speaker 50W max', 'brand' => 'CROWN', 'price' => '4850.00'],
            ['category' => 'HORN SPEAKERS', 'model' => 'HS-11', 'description' => '11" x 4" 180W horn speaker', 'brand' => 'CROWN', 'price' => '1350.00'],
            ['category' => 'HORN SPEAKERS', 'model' => 'HS-5X8', 'description' => '5" x 8" horn speaker', 'brand' => 'CROWN', 'price' => '690.00'],
        ];

        foreach ($rows as $row) {
            $price = $this->toDecimal($row['price'] ?? null);

            Product::updateOrCreate(
                [
                    'name' => (string) $row['model'],
                    'category' => $row['category'] ?? null,
                ],
                [
                    'sku' => null,
                    'brand' => $row['brand'] ?: null,
                    'model' => $row['model'] ?: null,
                    'description' => $row['description'] ?: null,
                    'purchase_price' => 0,
                    'selling_price' => $price,
                    'stock_quantity' => 0,
                    'minimum_stock' => 0,
                ]
            );
        }
    }

    private function toDecimal(null|string $value): float
    {
        if ($value === null) {
            return 0.0;
        }

        $clean = trim(str_replace([',', ' '], '', $value));
        if ($clean === '' || strtolower($clean) === 'null') {
            return 0.0;
        }

        return (float) $clean;
    }
}

